### ISSUE TITLE
Corpse Flower 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#12]
# About
![Corpse flower 01](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/e7d5488c-b1bd-4845-a8f9-b75f852ed02b)

dimensions : refer to real life scale

# Assignee
**Discord: Seyi** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
Can you please make the following updates to this model
1. Resolve the N-gons in the center of the flower
2. Update the UVs so that the UVs for the entire group fit on a single 1x1 tile without overlapping


![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/62bf50e2-85ea-4a06-83f0-01968221f5b8)

![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/05993575-abb2-4bdb-96ae-3dba4582c0a0)
