### ISSUE TITLE
Drinks Trolley - 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#14]
# About
![Drinks trolley](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/aa5e917d-1d57-4d19-9558-fd43bb1bec85)

Dimensions : width x depth x height 
30 x 18 x 36

# Assigned To
**Discord: Sarah** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
WIP Photo


![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/3ffa2947-e5a6-405e-8831-81fef0c3338a)

**Comment by Bekreth** [comment]
Can you please make the following updates to the models:
1. Center the group of objects on the world center
2. Remove the triangles (Mostly located on the base of your cylinders)
3. Remove the N-Gons (mostly on the sides of your glasses)
4. Update your UVs to all fit within a single tile
5. Reduce your face counts:
  1. Avoid creating additional geometry for labels as their appearance can be drive by texture maps
  2. Reduce the loops on your flat surfaces (railing on top of the mesh, the flat of the trays)
  3. Cut down on the segments on all of your cylinders. The cocktail shaker shows you did shows how few vertices you need to give the shape of a cylinder under smoothing.  I might recommend having 8 instead of 4, but many of your cylinders can be reduced
